#!/bin/bash

has_java=false
. /etc/os-release
case "$ID" in
    ubuntu|debian)
        for version in "11" "8"; do
            pkg_name=openjdk-${version}-jre-headless
            if ! dpkg-query --status ${pkg_name}; then
                continue
            fi
            java=$(dpkg -L ${pkg_name} | grep '/java$')
            if [ -n "$java" ]; then
                break
            fi
        done
        ;;
    fedora|centos)
        for version in "11" "1.8.0"; do
            pkg_name=java-${version}-openjdk-headless
            if ! rpm --quiet -q ${pkg_name}; then
                continue
            fi
            java=$(rpm -ql ${pkg_name} | grep '/java$')
            if [ -n "$java" ]; then
                break
            fi
        done
        ;;
esac
if [ -n "$java" ]; then
    has_java=true
elif [ -x /usr/bin/java ]; then
    javaver=$(/usr/bin/java -version 2>&1|head -n1|cut -f 3 -d " ")
    if [[ "$javaver" =~ ^\"1.8.0 || "$javaver" =~ ^\"11.0. ]]; then
        java=/usr/bin/java
        has_java=true
    fi
fi
if ! $has_java; then
    exit 1
fi

exec $java $*
