#!/bin/bash

function select_java_debian() {
    for version in "11" "8"; do
        pkg_name=openjdk-${version}-jre-headless
        if ! dpkg-query --status ${pkg_name}; then
            continue
        fi
        java=$(dpkg -L ${pkg_name} | grep '/java$')
        if [ -n "$java" ]; then
            echo $java
            return
        fi
    done
}

function select_java_fedora() {
    for version in "11" "1.8.0"; do
        pkg_name=java-${version}-openjdk-headless
        if ! rpm --quiet -q ${pkg_name}; then
            continue
        fi
        java=$(rpm -ql ${pkg_name} | grep '/java$')
        if [ -n "$java" ]; then
            echo $java
            return
        fi
    done
}

function select_java_others() {
    javaver=$(/usr/bin/java -version 2>&1|head -n1|cut -f 3 -d " ")
    if [[ "$javaver" =~ ^\"1.8.0 || "$javaver" =~ ^\"11.0. ]]; then
        echo /usr/bin/java
    fi
}

. /etc/os-release
case "$ID" in
    ubuntu|debian)
        java=$(select_java_debian)
        ;;
    fedora|centos)
        java=$(select_java_fedora)
        ;;
esac
if [ -n "$java" ]; then
    : # good
elif [ -x /usr/bin/java ]; then
    java=$(select_java_others)
fi
if [ -z "$java" ]; then
    exit 1
fi

exec $java $*
